import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const PRODUCTS = [
  {
    name: 'Granola Artesanal',
    category: 'granolas',
    emoji: '🥣',
    description: 'Granola artesanal libre de azúcar añadida. Perfecta para el desayuno.',
    flavors: ['Canela', 'Cacao'],
    sortOrder: 1,
    variants: [{ label: 'Unidad', price: 15000 }],
  },
  {
    name: 'Granola Premium con Proteína',
    category: 'granolas',
    emoji: '💪',
    description: 'Excelente fuente de proteína y fibra. Semillas, frutos secos, aceite de coco y stevia.',
    flavors: [],
    sortOrder: 2,
    variants: [{ label: '300gr', price: 39000 }],
  },
  {
    name: 'Pan Integral Artesanal',
    category: 'panaderia',
    emoji: '🍞',
    description: 'Panes integrales artesanales horneados cada día. Sin aditivos ni conservantes.',
    flavors: [],
    sortOrder: 3,
    variants: [
      { label: 'Mogolla Integral', price: 9800, sortOrder: 0 },
      { label: 'Tostada Integral', price: 8300, sortOrder: 1 },
      { label: 'Pan Tajado', price: 6300, sortOrder: 2 },
    ],
  },
  {
    name: 'Galletas Artesanales',
    category: 'snacks',
    emoji: '🍪',
    description: 'Galletas artesanales horneadas con ingredientes naturales seleccionados.',
    flavors: ['Sal Marina', 'Chocolate'],
    sortOrder: 4,
    variants: [{ label: 'Unidad', price: 14000 }],
  },
  {
    name: 'Crispetas con Proteína',
    category: 'snacks',
    emoji: '🍿',
    description: 'Crispetas artesanales enriquecidas con proteína. El snack ideal para cualquier momento.',
    flavors: ['Parmesano', 'Ajo', 'Caramelo', 'Salado', 'Limón Pimienta'],
    sortOrder: 5,
    variants: [{ label: 'Unidad', price: 12500 }],
  },
  {
    name: 'Papas Snack Natural',
    category: 'snacks',
    emoji: '🥔',
    description: 'Papas snack naturales y crujientes en sabores irresistibles. Sin colorantes artificiales.',
    flavors: ['Lima-Limón', 'Bbq Dulce', 'Sal Rosada'],
    sortOrder: 6,
    variants: [
      { label: '25gr', price: 3000, sortOrder: 0 },
      { label: '100gr', price: 12000, sortOrder: 1 },
    ],
  },
  {
    name: 'Chips de Plátano',
    category: 'snacks',
    emoji: '🍌',
    description: 'Chips de plátano natural sin gluten. Disponible en plátano verde y maduro.',
    flavors: ['Sal Marina', 'Lima-Limón'],
    sortOrder: 7,
    variants: [{ label: '30gr', price: 3000 }],
  },
  {
    name: 'Chicharrón Natural',
    category: 'snacks',
    emoji: '🥓',
    description: 'Chicharrón sin conservantes, súper crujiente y sabroso. Snack alto en proteína.',
    flavors: ['Lima-Limón', 'Sal Marina'],
    sortOrder: 8,
    variants: [
      { label: '30gr', price: 6000, sortOrder: 0 },
      { label: '90gr', price: 18000, sortOrder: 1 },
    ],
  },
  {
    name: 'Mini Galletas Saludables',
    category: 'snacks',
    emoji: '🍪',
    description: 'Con avena, semillas de chía y stevia. Dulces, nutritivas y sin culpa.',
    flavors: ['Chocolate', 'Frutos Rojos', 'Canela'],
    sortOrder: 9,
    variants: [{ label: 'Bolsa', price: 3000 }],
  },
  {
    name: 'Nuez de Brasil',
    category: 'frutos-secos',
    emoji: '🌰',
    description: 'Fuente natural de selenio y antioxidantes. Crudas y sin sal añadida.',
    flavors: [],
    sortOrder: 10,
    variants: [
      { label: '40gr', price: 6200, sortOrder: 0 },
      { label: '125gr', price: 17500, sortOrder: 1 },
      { label: '250gr', price: 35000, sortOrder: 2 },
      { label: '500gr', price: 61000, sortOrder: 3 },
    ],
  },
  {
    name: 'Maní Natural',
    category: 'frutos-secos',
    emoji: '🥜',
    description: 'Maní natural, excelente fuente de proteína vegetal. Solo o con uva pasa.',
    flavors: ['Maní + Uva Pasa', 'Maní Salado'],
    sortOrder: 11,
    variants: [
      { label: 'Salado 125gr', price: 5000, sortOrder: 0 },
      { label: '+ Uva Pasa 125gr', price: 5500, sortOrder: 1 },
      { label: '+ Uva Pasa 250gr', price: 8500, sortOrder: 2 },
      { label: '+ Uva Pasa 500gr', price: 16000, sortOrder: 3 },
    ],
  },
  {
    name: 'Almendras',
    category: 'frutos-secos',
    emoji: '🫘',
    description: 'Almendras naturales ricas en vitamina E, proteína y grasas saludables.',
    flavors: [],
    sortOrder: 12,
    variants: [
      { label: '50gr', price: 5600, sortOrder: 0 },
      { label: '125gr', price: 12700, sortOrder: 1 },
      { label: '500gr', price: 25000, sortOrder: 2 },
    ],
  },
  {
    name: 'Marañón (Cashew)',
    category: 'frutos-secos',
    emoji: '🌰',
    description: 'Marañón natural, cremoso y nutritivo. Fuente de vitaminas del complejo B.',
    flavors: [],
    sortOrder: 13,
    variants: [
      { label: '100gr', price: 16000, sortOrder: 0 },
      { label: '250gr', price: 27500, sortOrder: 1 },
    ],
  },
  {
    name: 'Mix Frutos Secos',
    category: 'frutos-secos',
    emoji: '🥜',
    description: 'Mix premium: almendra, nuez pecan, macadamia, nuez de brasil y marañón.',
    flavors: [],
    sortOrder: 14,
    variants: [
      { label: '50gr', price: 8000, sortOrder: 0 },
      { label: '100gr', price: 12500, sortOrder: 1 },
      { label: '250gr', price: 30000, sortOrder: 2 },
    ],
  },
  {
    name: 'Mix Armonía',
    category: 'frutos-secos',
    emoji: '✨',
    description: 'Mix especial de macadamia, marañón, semilla de calabaza y arándano deshidratado.',
    flavors: [],
    sortOrder: 15,
    variants: [{ label: '200gr', price: 25000 }],
  },
  {
    name: 'Flor de Jamaica',
    category: 'frutos-secos',
    emoji: '🌺',
    description: 'Flor de jamaica deshidratada rica en antioxidantes. Ideal para té o agua fresca.',
    flavors: [],
    sortOrder: 16,
    variants: [
      { label: '50gr', price: 8300, sortOrder: 0 },
      { label: '125gr', price: 20000, sortOrder: 1 },
    ],
  },
  {
    name: 'Arándanos Deshidratados',
    category: 'frutos-secos',
    emoji: '🫐',
    description: 'Arándanos deshidratados naturales, llenos de antioxidantes y vitaminas.',
    flavors: [],
    sortOrder: 17,
    variants: [{ label: '125gr', price: 11000 }],
  },
  {
    name: 'Semilla de Calabaza',
    category: 'frutos-secos',
    emoji: '🎃',
    description: 'Semillas de calabaza naturales, fuente de magnesio, zinc y proteína vegetal.',
    flavors: [],
    sortOrder: 18,
    variants: [{ label: '100gr', price: 8400 }],
  },
  {
    name: 'Yogurt Griego Premium 150g',
    category: 'lacteos',
    emoji: '🥛',
    description: 'Artesanal, endulzado con stevia. 11g de proteína por porción. Sin azúcares añadidas.',
    flavors: ['Vainilla', 'Vainilla+Coco', 'Vainilla+Piña', 'Coco', 'Vainilla+Fresa', 'Vainilla+Frutos Rojos', 'Vainilla+Arándanos'],
    sortOrder: 19,
    variants: [{ label: '150g', price: 8300 }],
  },
  {
    name: 'Yogurt Griego Entero 550g',
    category: 'lacteos',
    emoji: '🥛',
    description: 'Textura muy cremosa, hecho con leche entera. 14g de proteína. Sin azúcares añadidas.',
    flavors: [],
    sortOrder: 20,
    variants: [{ label: '550g', price: 26000 }],
  },
  {
    name: 'Yogurt Griego Natural 550g',
    category: 'lacteos',
    emoji: '🥛',
    description: 'Sin dulce, libre de grasa, sin edulcorantes. 13g de proteína por porción.',
    flavors: [],
    sortOrder: 21,
    variants: [{ label: '550g', price: 26000 }],
  },
  {
    name: 'Yogurt Griego Vainilla 550g',
    category: 'lacteos',
    emoji: '🥛',
    description: 'Premium artesanal sabor vainilla, endulzado con stevia. 11g de proteína.',
    flavors: [],
    sortOrder: 22,
    variants: [{ label: '550g', price: 26000 }],
  },
  {
    name: 'Kéfir de Sabores',
    category: 'lacteos',
    emoji: '🫙',
    description: '55 tipos de bacterias vivas. 10g de proteína. Libre de grasa. Sin azúcares añadidas.',
    flavors: ['Manzana', 'Kiwi', 'Sandía', 'Fresa', 'Piña', 'Hierbabuena', 'Sin Dulce'],
    sortOrder: 23,
    variants: [{ label: '1 Litro', price: 35000 }],
  },
  {
    name: 'Queso para Untar',
    category: 'lacteos',
    emoji: '🧀',
    description: 'Queso artesanal para untar, saludable y delicioso. Variedad Ricotta y Kéfir.',
    flavors: ['Queso Ricotta', 'Queso Kéfir'],
    sortOrder: 24,
    variants: [{ label: '270g', price: 19500 }],
  },
  {
    name: 'Postres de Yogurt Griego',
    category: 'lacteos',
    emoji: '🍮',
    description: 'Postres artesanales sin azúcares añadidas. Buena fuente de proteína.',
    flavors: ['Mousse de Maracuyá', 'Panna Cotta Choco & Avellanas', 'Pie de Limón'],
    sortOrder: 25,
    variants: [{ label: '180g', price: 12800 }],
  },
  {
    name: 'Magnesio',
    category: 'suplementos',
    emoji: '✨',
    description: '400+ funciones comprobadas. Reduce el estrés, mejora el sueño, alivia dolores de cabeza.',
    flavors: ['Limonada de Coco', 'Jengibre', 'Limonada Rosada'],
    sortOrder: 26,
    variants: [
      { label: 'Presentación básica', price: 30000, sortOrder: 0 },
      { label: 'Premium', price: 80000, sortOrder: 1 },
    ],
  },
  {
    name: 'Proteína de Hueso de Pollo',
    category: 'suplementos',
    emoji: '💪',
    description: '18g proteína + 9.9g colágeno por porción. Sin azúcar añadida, sin lácteos, sin químicos.',
    flavors: ['Caramelo', 'Vainilla', 'Chocolate'],
    sortOrder: 27,
    variants: [{ label: 'Tarro', price: 190000 }],
  },
  {
    name: 'InnerBloom',
    category: 'suplementos',
    emoji: '🌸',
    description: 'Equilibrio hormonal y metabólico femenino. Inositol, Vit. A/D/E, Hierro, Zinc, Metilfolato.',
    flavors: ['Frutos Rojos'],
    sortOrder: 28,
    variants: [{ label: 'Tarro', price: 170000 }],
  },
  {
    name: 'Mantequilla Ghee',
    category: 'aceites',
    emoji: '🧈',
    description: 'Mantequilla clarificada ayurveda. Para freír o untar. Antinflamatoria y antioxidante.',
    flavors: [],
    sortOrder: 29,
    variants: [
      { label: '200gr', price: 22000, sortOrder: 0 },
      { label: '420gr', price: 45000, sortOrder: 1 },
      { label: '640gr', price: 62000, sortOrder: 2 },
    ],
  },
  {
    name: 'Aceite de Coco',
    category: 'aceites',
    emoji: '🥥',
    description: 'Aceite de coco puro y natural. Ideal para cocinar, hornear y consumo directo.',
    flavors: [],
    sortOrder: 30,
    variants: [
      { label: '175gr', price: 15000, sortOrder: 0 },
      { label: '420gr', price: 30000, sortOrder: 1 },
    ],
  },
  {
    name: 'Vinagre de Manzana con la Madre',
    category: 'aceites',
    emoji: '🍎',
    description: 'Promueve pérdida de grasa, desintoxicante natural, mejora digestión y reduce colesterol.',
    flavors: [],
    sortOrder: 31,
    variants: [{ label: 'Frasco', price: 35000 }],
  },
  {
    name: 'Vinagre Especiado',
    category: 'aceites',
    emoji: '🌿',
    description: 'Vinagre de manzana potenciado con pimienta negra, penca de sábila y cúrcuma.',
    flavors: [],
    sortOrder: 32,
    variants: [{ label: 'Frasco', price: 38000 }],
  },
  {
    name: 'Avena y Harinas',
    category: 'harinas',
    emoji: '🌾',
    description: 'Avena en hojuelas y harinas especiales para una repostería más saludable y nutritiva.',
    flavors: [],
    sortOrder: 33,
    variants: [
      { label: 'Avena hojuelas 1kg', price: 30000, sortOrder: 0 },
      { label: 'Harina de avena', price: 38000, sortOrder: 1 },
      { label: 'Harina de almendra', price: 30000, sortOrder: 2 },
    ],
  },
  {
    name: 'Mezclas para Hornear',
    category: 'harinas',
    emoji: '🎂',
    description: 'Libres de gluten, azúcar, lácteos y conservantes. ¡Solo agrega ingredientes frescos!',
    flavors: ['Brownie', 'Vainilla', 'Banano'],
    sortOrder: 34,
    variants: [
      { label: 'Base de avena', price: 33000, sortOrder: 0 },
      { label: 'Base de almendra', price: 42000, sortOrder: 1 },
    ],
  },
  {
    name: 'Cremas Untables',
    category: 'cremas',
    emoji: '🍫',
    description: 'Artesanales, sin azúcar, sin lácteos, sin gluten. El indulgente saludable que buscabas.',
    flavors: ['Cacao y Avellanas', 'Cacao Avellanas Crocante', 'Pistacho'],
    sortOrder: 35,
    variants: [
      { label: 'Cacao y Avellanas', price: 48000, sortOrder: 0 },
      { label: 'Cacao Crocante', price: 58000, sortOrder: 1 },
      { label: 'Pistacho', price: 48000, sortOrder: 2 },
    ],
  },
  {
    name: 'Aguas Gasificadas',
    category: 'bebidas',
    emoji: '💧',
    description: 'Aguas gasificadas artesanales en sabores naturales. Refrescantes y sin azúcar añadida.',
    flavors: ['Flor de Jamaica', 'Uva', 'Hierbabuena', 'Arándano', 'Aloe Vera', 'Limón y Jengibre'],
    sortOrder: 36,
    variants: [{ label: 'Botella', price: 6500 }],
  },
  {
    name: 'Stevia Natural',
    category: 'edulcorantes',
    emoji: '🍃',
    description: 'Stevia artesanal en distintas presentaciones y sabores. Endulza sin calorías.',
    flavors: ['Natural', 'Vainilla', 'Caramelo'],
    sortOrder: 37,
    variants: [
      { label: '60ml', price: 14500, sortOrder: 0 },
      { label: '250ml', price: 30000, sortOrder: 1 },
    ],
  },
]

async function main() {
  console.log('🌱 Seeding database...')

  // Clear existing data
  await prisma.variant.deleteMany()
  await prisma.product.deleteMany()

  for (const product of PRODUCTS) {
    const { variants, ...productData } = product
    await prisma.product.create({
      data: {
        ...productData,
        variants: {
          create: variants.map((v, i) => ({
            label: v.label,
            price: v.price,
            sortOrder: ('sortOrder' in v ? v.sortOrder : i) as number,
          })),
        },
      },
    })
  }

  console.log(`✅ Seeded ${PRODUCTS.length} products successfully!`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
